# Generated by Django 4.1.7 on 2023-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasktodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=20)),
                ('dete', models.DateField()),
            ],
        ),
    ]
