# Generated by Django 4.1.7 on 2023-05-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktodo',
            old_name='Title_name',
            new_name='Title',
        ),
    ]
