# Generated by Django 4.1.7 on 2023-05-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_title_name_tasktodo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktodo',
            old_name='dete',
            new_name='date',
        ),
    ]
