# Generated by Django 4.1.7 on 2023-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_rename_category_tasktodo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tasktodo',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tasktodo',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
