# Generated by Django 4.1.7 on 2023-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_tasktodo_category_alter_tasktodo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
